# Site wide configuration

title: Bradonomics
description: The Blog of Brad West
logo: brad-west-logo-160x120.jpg # 120x120 px default image used for Twitter summary card
teaser: brad-west-theme-300x225.jpg # 400x250 px default teaser image used in image archive grid
baseurl: /
url: http://bradonomics.com

# Jekyll configuration

paginate: 5
permalink: /:title/
markdown: kramdown
highlighter: pygments
encoding: utf-8
sass:
  sass_dir: _sass
  style: compressed

# Site navigation links

navigation:
- title: Home
  url: /

# Site owner info

owner:
  name: Brad West
  email: brad@bradonomics.com
  twitter: bradonomics
  google: /103163741383795666289/
  bio: American Expat in Thailand - Permaculture Nerd - Brazilian Jiu-Jitsu Enthusiast - Philomath - Armchair Linguist
  avatar: Brad_West_bio.jpg # 160x160 px image for author byline

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]